### ISSUE TITLE
Not able to build latest tiGigya module with the sample project

### ISSUE THREAD

**Issue by NagarjunaReddy** [appersonlabs/TiGigya#12]
We are getting below error when we try to build a sample app including the latest iOS gigya module
error in studio-
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/SchwansHomeService.build/Release-iphoneos/SchwansHomeService.build/Objects-normal/arm64/SchwansHomeService normal arm64
[ERROR] :  	Ld build/SchwansHomeService.build/Release-iphoneos/SchwansHomeService.build/Objects-normal/armv7/SchwansHomeService normal armv7
[ERROR] :  (2 failures)

Xcode error - 
ld: warning: directory not found for option '-F/Users/pc270526/Downloads/RR300PRD-2/build/iphone/../../modules/iphone/com.appersonlabs.gigya/1.0.0/platform'
ld: warning: directory not found for option '-F/Library/Application Support/Titanium/modules/iphone/com.appersonlabs.gigya/1.0.0/platform'
ld: warning: directory not found for option '-F/Users/pc270526/Library/Application Support/Titanium/modules/iphone/com.appersonlabs.gigya/1.0.0/platform'
ld: framework not found GigyaSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iotashan** [comment]
You are not using the latest version, which is 1.1.0 for iOS.

**Comment by NagarjunaReddy** [comment]
Now am using the latest one and having a issue with Facebook. Am not seeing the facebook option to login when I call showLoginProvidersDialog and loginToProvider is not working when I pass 'facebook' as a parameter.

Please let me know If I need to add anything else to make use of Facebook option?

**Comment by iotashan** [comment]
You will need to add the Facebook module to your app, and properly configure it.
