### ISSUE TITLE
Android Lollipop login issue after logout

### ISSUE THREAD

**Issue by wversluys** [appersonlabs/TiGigya#9]
I'm experiencing an issue with this module after logging out of gigya when using a device with Android Lollipop. I am able to login to Gigya using this module, but after I logout I cannot login again. This does work on older Android versions and iOS.

You can reproduce this by running the sample code on any device with OS Android Lollipop.

Is this an issue related to this module or is it something the Gigya SDK does not support yet?

**Comment by mattapperson** [comment]
This seems to be an issue with the gigya sdk as I have found reports of this from native apps as well
